[build]
  publish = "out"
  command = "npm run build"

# Gestion des pages dynamiques Next.js - routes spécifiques en premier
[[redirects]]
  from = "/commune/:code_insee"
  to = "/commune/:code_insee/index.html"
  status = 200

[[redirects]]
  from = "/commune/:code_insee/comparaison"
  to = "/commune/:code_insee/comparaison/index.html"
  status = 200

# Fallback pour toutes les autres routes (SPA) - doit être en dernier
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers de sécurité - Autorisation d'embedding pour WordPress
[[headers]]
  for = "/*"
  [headers.values]
    # X-Frame-Options supprimé pour permettre l'embedding
    # Content-Security-Policy avec frame-ancestors pour plus de contrôle
    Content-Security-Policy = "frame-ancestors *"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 

# Headers spécifiques pour les assets statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 