[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  # Nouveau token Mapbox avec restrictions de domaine configurées
  NEXT_PUBLIC_MAPBOX_TOKEN = "pk.eyJ1IjoibWJyb3V0aW4iLCJhIjoiY21jMjVpbG5nMDVnMjJscXhrYjU4NDJpdCJ9.nwr3N3oiuU3MXdnN2X62Qw"

# Gestion des pages dynamiques Next.js - routes spécifiques en premier
[[redirects]]
  from = "/commune/:code_insee"
  to = "/commune/:code_insee/index.html"
  status = 200

[[redirects]]
  from = "/commune/:code_insee/comparaison"
  to = "/commune/:code_insee/comparaison/index.html"
  status = 200

# Fallback pour toutes les autres routes (SPA) - doit être en dernier
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers spécifiques pour les assets statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 